CRUD/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # path('Student/',include('Student.urls',namespace='Student')),
    path('',include('Student.urls',namespace='Student')),
    path('admin/', admin.site.urls),
]

Student/urls.py
from django.urls import path

from Student import views

app_name = 'Student'

urlpatterns = [
    path('', views.add_student, name='add_student'),
    path('student_manage', views.student_manage, name='student_manage'),
    path('student_edit/<int:pk>', views.student_edit, name='student_edit'),
    path('delete_student/<int:pk>', views.delete_student, name='delete_student'),
    path('show_graph', views.show_graph, name='show_graph'),
    
    path('fetch_sensor_values_ajax', views.fetch_sensor_values_ajax, name='fetch_sensor_values_ajax'),

]

Student/models.py
from django.db import models




class StudentModel(models.Model):
    name = models.CharField(' Name',max_length=200 )
    age = models.IntegerField('Age')
    address=models.TextField()
    email=models.EmailField(default="")
    pin=models.IntegerField(default=0)
    mob=models.IntegerField(default=0)

    def __str__(self):
        return self.name

Student/forms.py
from django import forms
from .models import StudentModel


class StudentForm(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter Name here '
    }))
    age = forms.CharField( max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Age '
    }))
    address = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Address '
    }))
    email = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email '
    }))
    pin = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'PIN '
    }))

    mob = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Mobile '
    }))
    class Meta():
        model=StudentModel
        fields=['name','age','address','email','pin','mob']

Student/views.py
from datetime import datetime
import random
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import StudentForm
from .models import StudentModel





def add_student(request, template_name='student_add.html'):
    form = StudentForm(request.POST or None)
    if form.is_valid():
        form.save()
        # return  HttpResponse("ok saved")
        return redirect('Student:student_manage')
    return render(request, template_name, {'form':form})


def student_manage(request, template_name='student_manage.html'):
    std_data = StudentModel.objects.all() ###   select * from Student(table)
    data = {}
    data['object_list'] = std_data
    return render(request, template_name, data)


def student_edit(request, pk, template_name='student_add.html'):
    book= get_object_or_404(StudentModel, pk=pk)### select * from student where id=pk(parameterized id),pk means primary key
    form = StudentForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('Student:student_manage')
    return render(request, template_name, {'form':form})

def delete_student(request, pk):
    obj = get_object_or_404(StudentModel, pk=pk)
    obj.delete()
    return redirect('Student:student_manage')



def show_graph(request,template_name='live_graph.html'):
    return render(request,template_name)


def fetch_sensor_values_ajax(request):
    data={}
    if request.is_ajax():
            com_port = request.GET.get('id', None)
            sensor_val=random.random() # auto random value if sendor is not connected , you can remove this line
            sensor_data=[]
            now=datetime.now()
            ok_date=str(now.strftime('%Y-%m-%d %H:%M:%S'))
            try:

                # sr=serial.Serial("COM9",9600)
                sr=serial.Serial(com_port,9600)
                st=list(str(sr.readline(),'utf-8'))
                sr.close()
                sensor_val=str(''.join(st[:]))
                if(sensor_val):
                    sensor_data.append(str(sensor_val)+','+ok_date)
                else:
                    sensor_data.append(str(sensor_val)+','+ok_date)
            except Exception as e:
                    sensor_data.append(str(sensor_val)+','+ok_date)
            data['result']=sensor_data
    else:
        data['result']='Not Ajax'
    return JsonResponse(data)

Student/templates/live_graph.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% load static %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'font-awesome.css' %}"> 
<script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
<center><h1>Live Graph</h1></center>
<hr>
    
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-4"><label>Enter Com Port:</label></div>
            <div class="col-md-4">
                <input type="text" class="form-control col-md-2" name="com" id="comport">
            </div>
            <div class="col-md-4">
                <input type="submit" name="submit" id="btn_show" class="btn btn-primary">
            </div>
        </div>
    </div>
     
<br><br>
<hr/>
<div class="row">
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
</div>

</div>
</body>

<script src="{% static 'jquery-3.3.1.min.js' %}"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>


<script>
$("#btn_show").click(function(){
    com=$("#comport").val();
    fill_graph_sensor(com);
});


function fill_graph_sensor(){
        var dps = []; // dataPoints
var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title: {
		text: "Live Data from Arduino connected with sensor"
	},
	axisX: {
		title: "Time"
	},
	axisY: {
		title: "data",
		suffix: ""
	},
	data: [{
		type: "line",
		name: "CPU Utilization",
		connectNullData: true,
		//nullDataLineDashType: "solid",
		xValueType: "dateTime",
		xValueFormatString: "DD MMM hh:mm TT",
		yValueFormatString: "#,##0.##\"mm\"",
		dataPoints: dps
	}]
});

var xVal = 0;
var yVal = 100;
var updateInterval = 4000;//miliseconds
var dataLength = 20; // number of dataPoints visible at any point

var updateChart = function () {

    $.ajax({
            type:"get",
            url: "{% url 'Student:fetch_sensor_values_ajax' %}",
            data: {
                     'id': com
                   },
            success: function(data) {
                console.log(data.result);
                for(index = 0; index < data.result.length; index++) {
                    var str_array = data.result[index].split(',');
                    dps.push({
			            x: Date.parse(str_array[1]),
			            y: Number(str_array[0])
		            });
                   }
                return data;
                    },
            error: function(){
                    console.log("error he ji");
                 }
            });

	if (dps.length > dataLength) {
		dps.shift();
	}

	chart.render();
};

updateChart(dataLength);
setInterval(function(){updateChart()}, updateInterval);
}
</script>
</html>

Student/templates/live_graph_.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Live Graph</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        {% load staticfiles %}
        <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

</head>
<body>
    <center>
    <label>Enter Com PORT:</label>
    <input type="text" class="form-control col-md-2" name="com" id="comport">
    <input type="submit" name="submit" id="btn_show" class="btn btn-primary">
    <h1>Live data from Arduino Sensor</h1>
        </center>

    <div id="chartContainer" style="height: 450px; width:100%;"></div>
</body>
<script>
$("#btn_show").click(function(){
    com=$("#comport").val();
    fill_graph_sensor(com);

});
function fill_graph_sensor(){

    var dps = []; // dataPoints
var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title: {
		text: "Live Data"
	},
	axisX: {
		title: "Time"
	},
	axisY: {
		title: "data",
		suffix: ""
	},
	data: [{
		type: "line",
		name: "CPU Utilization",
		connectNullData: true,
		//nullDataLineDashType: "solid",
		xValueType: "dateTime",
		xValueFormatString: "DD MMM hh:mm TT",
		yValueFormatString: "#,##0.##\"mm\"",
		dataPoints: dps
	}]
});

var xVal = 0;
var yVal = 100;
var updateInterval = 4000;
var dataLength = 20; // number of dataPoints visible at any point

var updateChart = function () {

    $.ajax({
            type:"get",
            url: "{% url 'Student:fetch_sensor_values_ajax' %}",
            data: {
                     'id': com
                   },
            success: function(data) {
                console.log(data.result);
                for(index = 0; index < data.result.length; index++) {
                    var str_array = data.result[index].split(',');
                    dps.push({
			            x: Date.parse(str_array[1]),
			            y: Number(str_array[0])
		            });
                   }
                return data;
                    },
            error: function(){
                    console.log("error he ji");
                 }
            });

	if (dps.length > dataLength) {
		dps.shift();
	}

	chart.render();
};

updateChart(dataLength);
setInterval(function(){updateChart()}, updateInterval);


}
</script>
</html>

Student/templates/student_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% load static %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'font-awesome.css' %}"> 
<script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <section class="col-md-12">
            <h1 class="page-header">Add Student <h4>here you can insert student basic info</h4></h1>

            <div class="row text-center">
                    <div class="col-md-12">
                        <a class="btn btn-primary" href="{% url 'Student:student_manage' %}">see The List of All Student</a>
                        <a class="btn btn-primary " href="{% url 'Student:show_graph' %}">Real-time data from Sensor</a>
                    </div>
            </div>
            <hr>
            <!-- Table content -->
            <div class="row">
                <div class="form-group">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}


                        <div class="form-group">
                            <table  class="table table-responsive table-bordered">
                            {{ form.as_table }}
                                </table>
                            <input type="submit" class="btn btn-primary" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
</body>
</html>
<script src="{% static 'jquery-3.3.1.min.js' %}"></script>

Student/templates/student_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'font-awesome.css' %}"> 

<script src="{% static 'jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>

</head>
<body>
<div class="container">
    <div class="row">
<section class="col-md-12">
    <h1 class="page-header">Manage Student</h1>
    <div class="row text-center">
        <div class="col-md-12">
            <a class="btn btn-primary " href="{% url 'Student:add_student' %}">Add Student</a>
             <a class="btn btn-primary " href="{% url 'Student:show_graph' %}">Real-time data from Sensor</a>
        </div>
    </div>
    <hr>
    <!-- Table content -->
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered" id="content">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th> Name</th>
                            <th>Email</th>
                            <th>Mob</th>
                            <th class="text-center" colspan="2">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                            {% for book in object_list %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.name }}</td>
                            <td>{{ book.email }}</td>
                            <td>{{ book.mob }}</td>


                            <td class="text-center"><a href="{% url 'Student:student_edit' book.id %}" title="Edit Employee."><span class="btn btn-success">Edit</span></a></td>
                            <td class="text-center"><a  class="delete"
                                data-url="{% url 'Student:delete_student' book.id %}" title="Delete Student."><span
                                class="btn btn-danger">Delete</span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div><!--end Table content -->
</section>
        </div>
</div>




  /*<!-- The Modal -->
  <div class="modal" id="update_info" >
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Are you sure?</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
         Do you really want to delete these records? This process cannot be undone.
        </div>
        
        <!-- Modal footer -->
         <div class="modal-footer">
                <a id="sureDelete">
                    <button type="button" class="btn btn-danger" id="delete">Yes</button>
                </a>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>

            </div>
        
      </div>
    </div>
  </div>
</body>
</html>



<script>
        $(document.body).on("click", ".delete", function () {
            $("#sureDelete").attr("href", $(this).data('url'));
            $('#update_info').modal('show');

        });
</script>